servers:
  - name: "Example Name" 
    port: 8080
    proxy_timeout : 10
    rate_limit: 10
    # tcp_proxy_pass: 
    #       addresses:
    #         - "127.0.0.1:6379"
    #       downstream_timeout: 10
    #       loadbalancing: "random"


    http: true
    endpoints:
      - name: '/'
        proxy_set_headers:
          - header_name: "name"
            header_value: "value"
        proxy_pass:
          addresses:
            - "127.0.0.1:6379"
          downstream_timeout: 10
          loadbalancing: "random"
          health_check: 
            enabled: false
            interval: 60
            fails: 3
            passes: 1
log_level: "DEBUG"
